version: '3'

tasks:

  generate:
    desc: "Run all generators"
    aliases:
      - gen
    cmds:
      - task protoc-generate
      - task go-generate

  protoc-generate:
    desc: "Generate protobuf files"
    aliases:
      - protoc
      - pg
    cmds:
      - |
        protoc --go_out=api --go_opt=paths=source_relative \
        --go-grpc_out=api --go-grpc_opt=paths=source_relative \
        proto/card_validator.proto

  go-generate:
    desc: "Run go code generators"
    aliases:
      - gogen
      - gg
    cmds:
      - go generate ./...

  test:
    desc: "Run all tests"
    aliases:
      - t
    cmds:
      - go test ./... -coverprofile cover.out
