version: '3'

tasks:

  protoc-generate:
    desc: "Generate protobuf files"
    aliases:
      - protoc
      - pg
    cmds:
      - |
        protoc --go_out=api --go_opt=paths=source_relative \
        --go-grpc_out=api --go-grpc_opt=paths=source_relative \
        proto/card_validator.proto

